system_error: correct ELAST emulation on Windows
ELAST should point to the last valid error string value.  However,
`_sys_nerr` provides the number of elements in the errlist array.  Since
the index is 0-based, this is off-by-one.  Adjust it accordingly.

Thanks to David Majnemer for catching this!

llvm-svn: 291336
GitOrigin-RevId: 49a10e1c07bdda958fee7ddc9333e50cb8d08507